services:
  blog:
    container_name: blog-container
    build:
      context: .
    image: bootcamp-blog
    ports:
      - 9091:8080
    environment:
      DB_URL: "jdbc:postgresql://db/postgres"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "pass"

  db:
    container_name: postgres-container
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 9092:5432
